////////////////////////////////////////////////////// AUTOGENERATED //////////////////////////////////////////////////////
// WARNING: All code changes to this file will be lost upon regeneration.                                                //
// Autogenerated on 2020-05-16 17:34:10:743966                                                                           //
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

using System.Runtime.CompilerServices;
using System;


namespace Unknown6656.Common
{
    public static class Currying
    {

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action Curry<T0>(this Action<T0> f, T0 arg0) => () => f(arg0);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T1> Curry<T0, T1>(this Func<T0, T1> f, T0 arg0) => () => f(arg0);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action<T1> Curry<T0, T1>(this Action<T0, T1> f, T0 arg0) => (arg1) => f(arg0, arg1);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T1, T2> Curry<T0, T1, T2>(this Func<T0, T1, T2> f, T0 arg0) => (arg1) => f(arg0, arg1);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action Curry<T0, T1>(this Action<T0, T1> f, T0 arg0, T1 arg1) => () => f(arg0, arg1);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T2> Curry<T0, T1, T2>(this Func<T0, T1, T2> f, T0 arg0, T1 arg1) => () => f(arg0, arg1);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action<T1, T2> Curry<T0, T1, T2>(this Action<T0, T1, T2> f, T0 arg0) => (arg1, arg2) => f(arg0, arg1, arg2);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T1, T2, T3> Curry<T0, T1, T2, T3>(this Func<T0, T1, T2, T3> f, T0 arg0) => (arg1, arg2) => f(arg0, arg1, arg2);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action<T2> Curry<T0, T1, T2>(this Action<T0, T1, T2> f, T0 arg0, T1 arg1) => (arg2) => f(arg0, arg1, arg2);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T2, T3> Curry<T0, T1, T2, T3>(this Func<T0, T1, T2, T3> f, T0 arg0, T1 arg1) => (arg2) => f(arg0, arg1, arg2);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action Curry<T0, T1, T2>(this Action<T0, T1, T2> f, T0 arg0, T1 arg1, T2 arg2) => () => f(arg0, arg1, arg2);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T3> Curry<T0, T1, T2, T3>(this Func<T0, T1, T2, T3> f, T0 arg0, T1 arg1, T2 arg2) => () => f(arg0, arg1, arg2);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action<T1, T2, T3> Curry<T0, T1, T2, T3>(this Action<T0, T1, T2, T3> f, T0 arg0) => (arg1, arg2, arg3) => f(arg0, arg1, arg2, arg3);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T1, T2, T3, T4> Curry<T0, T1, T2, T3, T4>(this Func<T0, T1, T2, T3, T4> f, T0 arg0) => (arg1, arg2, arg3) => f(arg0, arg1, arg2, arg3);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action<T2, T3> Curry<T0, T1, T2, T3>(this Action<T0, T1, T2, T3> f, T0 arg0, T1 arg1) => (arg2, arg3) => f(arg0, arg1, arg2, arg3);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T2, T3, T4> Curry<T0, T1, T2, T3, T4>(this Func<T0, T1, T2, T3, T4> f, T0 arg0, T1 arg1) => (arg2, arg3) => f(arg0, arg1, arg2, arg3);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action<T3> Curry<T0, T1, T2, T3>(this Action<T0, T1, T2, T3> f, T0 arg0, T1 arg1, T2 arg2) => (arg3) => f(arg0, arg1, arg2, arg3);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T3, T4> Curry<T0, T1, T2, T3, T4>(this Func<T0, T1, T2, T3, T4> f, T0 arg0, T1 arg1, T2 arg2) => (arg3) => f(arg0, arg1, arg2, arg3);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action Curry<T0, T1, T2, T3>(this Action<T0, T1, T2, T3> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3) => () => f(arg0, arg1, arg2, arg3);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T4> Curry<T0, T1, T2, T3, T4>(this Func<T0, T1, T2, T3, T4> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3) => () => f(arg0, arg1, arg2, arg3);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action<T1, T2, T3, T4> Curry<T0, T1, T2, T3, T4>(this Action<T0, T1, T2, T3, T4> f, T0 arg0) => (arg1, arg2, arg3, arg4) => f(arg0, arg1, arg2, arg3, arg4);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T1, T2, T3, T4, T5> Curry<T0, T1, T2, T3, T4, T5>(this Func<T0, T1, T2, T3, T4, T5> f, T0 arg0) => (arg1, arg2, arg3, arg4) => f(arg0, arg1, arg2, arg3, arg4);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action<T2, T3, T4> Curry<T0, T1, T2, T3, T4>(this Action<T0, T1, T2, T3, T4> f, T0 arg0, T1 arg1) => (arg2, arg3, arg4) => f(arg0, arg1, arg2, arg3, arg4);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T2, T3, T4, T5> Curry<T0, T1, T2, T3, T4, T5>(this Func<T0, T1, T2, T3, T4, T5> f, T0 arg0, T1 arg1) => (arg2, arg3, arg4) => f(arg0, arg1, arg2, arg3, arg4);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action<T3, T4> Curry<T0, T1, T2, T3, T4>(this Action<T0, T1, T2, T3, T4> f, T0 arg0, T1 arg1, T2 arg2) => (arg3, arg4) => f(arg0, arg1, arg2, arg3, arg4);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T3, T4, T5> Curry<T0, T1, T2, T3, T4, T5>(this Func<T0, T1, T2, T3, T4, T5> f, T0 arg0, T1 arg1, T2 arg2) => (arg3, arg4) => f(arg0, arg1, arg2, arg3, arg4);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action<T4> Curry<T0, T1, T2, T3, T4>(this Action<T0, T1, T2, T3, T4> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3) => (arg4) => f(arg0, arg1, arg2, arg3, arg4);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T4, T5> Curry<T0, T1, T2, T3, T4, T5>(this Func<T0, T1, T2, T3, T4, T5> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3) => (arg4) => f(arg0, arg1, arg2, arg3, arg4);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action Curry<T0, T1, T2, T3, T4>(this Action<T0, T1, T2, T3, T4> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4) => () => f(arg0, arg1, arg2, arg3, arg4);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T5> Curry<T0, T1, T2, T3, T4, T5>(this Func<T0, T1, T2, T3, T4, T5> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4) => () => f(arg0, arg1, arg2, arg3, arg4);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action<T1, T2, T3, T4, T5> Curry<T0, T1, T2, T3, T4, T5>(this Action<T0, T1, T2, T3, T4, T5> f, T0 arg0) => (arg1, arg2, arg3, arg4, arg5) => f(arg0, arg1, arg2, arg3, arg4, arg5);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T1, T2, T3, T4, T5, T6> Curry<T0, T1, T2, T3, T4, T5, T6>(this Func<T0, T1, T2, T3, T4, T5, T6> f, T0 arg0) => (arg1, arg2, arg3, arg4, arg5) => f(arg0, arg1, arg2, arg3, arg4, arg5);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action<T2, T3, T4, T5> Curry<T0, T1, T2, T3, T4, T5>(this Action<T0, T1, T2, T3, T4, T5> f, T0 arg0, T1 arg1) => (arg2, arg3, arg4, arg5) => f(arg0, arg1, arg2, arg3, arg4, arg5);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T2, T3, T4, T5, T6> Curry<T0, T1, T2, T3, T4, T5, T6>(this Func<T0, T1, T2, T3, T4, T5, T6> f, T0 arg0, T1 arg1) => (arg2, arg3, arg4, arg5) => f(arg0, arg1, arg2, arg3, arg4, arg5);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action<T3, T4, T5> Curry<T0, T1, T2, T3, T4, T5>(this Action<T0, T1, T2, T3, T4, T5> f, T0 arg0, T1 arg1, T2 arg2) => (arg3, arg4, arg5) => f(arg0, arg1, arg2, arg3, arg4, arg5);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T3, T4, T5, T6> Curry<T0, T1, T2, T3, T4, T5, T6>(this Func<T0, T1, T2, T3, T4, T5, T6> f, T0 arg0, T1 arg1, T2 arg2) => (arg3, arg4, arg5) => f(arg0, arg1, arg2, arg3, arg4, arg5);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action<T4, T5> Curry<T0, T1, T2, T3, T4, T5>(this Action<T0, T1, T2, T3, T4, T5> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3) => (arg4, arg5) => f(arg0, arg1, arg2, arg3, arg4, arg5);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T4, T5, T6> Curry<T0, T1, T2, T3, T4, T5, T6>(this Func<T0, T1, T2, T3, T4, T5, T6> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3) => (arg4, arg5) => f(arg0, arg1, arg2, arg3, arg4, arg5);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action<T5> Curry<T0, T1, T2, T3, T4, T5>(this Action<T0, T1, T2, T3, T4, T5> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4) => (arg5) => f(arg0, arg1, arg2, arg3, arg4, arg5);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T5, T6> Curry<T0, T1, T2, T3, T4, T5, T6>(this Func<T0, T1, T2, T3, T4, T5, T6> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4) => (arg5) => f(arg0, arg1, arg2, arg3, arg4, arg5);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action Curry<T0, T1, T2, T3, T4, T5>(this Action<T0, T1, T2, T3, T4, T5> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5) => () => f(arg0, arg1, arg2, arg3, arg4, arg5);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T6> Curry<T0, T1, T2, T3, T4, T5, T6>(this Func<T0, T1, T2, T3, T4, T5, T6> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5) => () => f(arg0, arg1, arg2, arg3, arg4, arg5);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action<T1, T2, T3, T4, T5, T6> Curry<T0, T1, T2, T3, T4, T5, T6>(this Action<T0, T1, T2, T3, T4, T5, T6> f, T0 arg0) => (arg1, arg2, arg3, arg4, arg5, arg6) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T1, T2, T3, T4, T5, T6, T7> Curry<T0, T1, T2, T3, T4, T5, T6, T7>(this Func<T0, T1, T2, T3, T4, T5, T6, T7> f, T0 arg0) => (arg1, arg2, arg3, arg4, arg5, arg6) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action<T2, T3, T4, T5, T6> Curry<T0, T1, T2, T3, T4, T5, T6>(this Action<T0, T1, T2, T3, T4, T5, T6> f, T0 arg0, T1 arg1) => (arg2, arg3, arg4, arg5, arg6) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T2, T3, T4, T5, T6, T7> Curry<T0, T1, T2, T3, T4, T5, T6, T7>(this Func<T0, T1, T2, T3, T4, T5, T6, T7> f, T0 arg0, T1 arg1) => (arg2, arg3, arg4, arg5, arg6) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action<T3, T4, T5, T6> Curry<T0, T1, T2, T3, T4, T5, T6>(this Action<T0, T1, T2, T3, T4, T5, T6> f, T0 arg0, T1 arg1, T2 arg2) => (arg3, arg4, arg5, arg6) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T3, T4, T5, T6, T7> Curry<T0, T1, T2, T3, T4, T5, T6, T7>(this Func<T0, T1, T2, T3, T4, T5, T6, T7> f, T0 arg0, T1 arg1, T2 arg2) => (arg3, arg4, arg5, arg6) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action<T4, T5, T6> Curry<T0, T1, T2, T3, T4, T5, T6>(this Action<T0, T1, T2, T3, T4, T5, T6> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3) => (arg4, arg5, arg6) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T4, T5, T6, T7> Curry<T0, T1, T2, T3, T4, T5, T6, T7>(this Func<T0, T1, T2, T3, T4, T5, T6, T7> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3) => (arg4, arg5, arg6) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action<T5, T6> Curry<T0, T1, T2, T3, T4, T5, T6>(this Action<T0, T1, T2, T3, T4, T5, T6> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4) => (arg5, arg6) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T5, T6, T7> Curry<T0, T1, T2, T3, T4, T5, T6, T7>(this Func<T0, T1, T2, T3, T4, T5, T6, T7> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4) => (arg5, arg6) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action<T6> Curry<T0, T1, T2, T3, T4, T5, T6>(this Action<T0, T1, T2, T3, T4, T5, T6> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5) => (arg6) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T6, T7> Curry<T0, T1, T2, T3, T4, T5, T6, T7>(this Func<T0, T1, T2, T3, T4, T5, T6, T7> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5) => (arg6) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action Curry<T0, T1, T2, T3, T4, T5, T6>(this Action<T0, T1, T2, T3, T4, T5, T6> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6) => () => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T7> Curry<T0, T1, T2, T3, T4, T5, T6, T7>(this Func<T0, T1, T2, T3, T4, T5, T6, T7> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6) => () => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action<T1, T2, T3, T4, T5, T6, T7> Curry<T0, T1, T2, T3, T4, T5, T6, T7>(this Action<T0, T1, T2, T3, T4, T5, T6, T7> f, T0 arg0) => (arg1, arg2, arg3, arg4, arg5, arg6, arg7) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T1, T2, T3, T4, T5, T6, T7, T8> Curry<T0, T1, T2, T3, T4, T5, T6, T7, T8>(this Func<T0, T1, T2, T3, T4, T5, T6, T7, T8> f, T0 arg0) => (arg1, arg2, arg3, arg4, arg5, arg6, arg7) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action<T2, T3, T4, T5, T6, T7> Curry<T0, T1, T2, T3, T4, T5, T6, T7>(this Action<T0, T1, T2, T3, T4, T5, T6, T7> f, T0 arg0, T1 arg1) => (arg2, arg3, arg4, arg5, arg6, arg7) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T2, T3, T4, T5, T6, T7, T8> Curry<T0, T1, T2, T3, T4, T5, T6, T7, T8>(this Func<T0, T1, T2, T3, T4, T5, T6, T7, T8> f, T0 arg0, T1 arg1) => (arg2, arg3, arg4, arg5, arg6, arg7) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action<T3, T4, T5, T6, T7> Curry<T0, T1, T2, T3, T4, T5, T6, T7>(this Action<T0, T1, T2, T3, T4, T5, T6, T7> f, T0 arg0, T1 arg1, T2 arg2) => (arg3, arg4, arg5, arg6, arg7) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T3, T4, T5, T6, T7, T8> Curry<T0, T1, T2, T3, T4, T5, T6, T7, T8>(this Func<T0, T1, T2, T3, T4, T5, T6, T7, T8> f, T0 arg0, T1 arg1, T2 arg2) => (arg3, arg4, arg5, arg6, arg7) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action<T4, T5, T6, T7> Curry<T0, T1, T2, T3, T4, T5, T6, T7>(this Action<T0, T1, T2, T3, T4, T5, T6, T7> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3) => (arg4, arg5, arg6, arg7) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T4, T5, T6, T7, T8> Curry<T0, T1, T2, T3, T4, T5, T6, T7, T8>(this Func<T0, T1, T2, T3, T4, T5, T6, T7, T8> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3) => (arg4, arg5, arg6, arg7) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action<T5, T6, T7> Curry<T0, T1, T2, T3, T4, T5, T6, T7>(this Action<T0, T1, T2, T3, T4, T5, T6, T7> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4) => (arg5, arg6, arg7) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T5, T6, T7, T8> Curry<T0, T1, T2, T3, T4, T5, T6, T7, T8>(this Func<T0, T1, T2, T3, T4, T5, T6, T7, T8> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4) => (arg5, arg6, arg7) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action<T6, T7> Curry<T0, T1, T2, T3, T4, T5, T6, T7>(this Action<T0, T1, T2, T3, T4, T5, T6, T7> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5) => (arg6, arg7) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T6, T7, T8> Curry<T0, T1, T2, T3, T4, T5, T6, T7, T8>(this Func<T0, T1, T2, T3, T4, T5, T6, T7, T8> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5) => (arg6, arg7) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action<T7> Curry<T0, T1, T2, T3, T4, T5, T6, T7>(this Action<T0, T1, T2, T3, T4, T5, T6, T7> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6) => (arg7) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T7, T8> Curry<T0, T1, T2, T3, T4, T5, T6, T7, T8>(this Func<T0, T1, T2, T3, T4, T5, T6, T7, T8> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6) => (arg7) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action Curry<T0, T1, T2, T3, T4, T5, T6, T7>(this Action<T0, T1, T2, T3, T4, T5, T6, T7> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7) => () => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T8> Curry<T0, T1, T2, T3, T4, T5, T6, T7, T8>(this Func<T0, T1, T2, T3, T4, T5, T6, T7, T8> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7) => () => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action<T1, T2, T3, T4, T5, T6, T7, T8> Curry<T0, T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T0, T1, T2, T3, T4, T5, T6, T7, T8> f, T0 arg0) => (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9> Curry<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>(this Func<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9> f, T0 arg0) => (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action<T2, T3, T4, T5, T6, T7, T8> Curry<T0, T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T0, T1, T2, T3, T4, T5, T6, T7, T8> f, T0 arg0, T1 arg1) => (arg2, arg3, arg4, arg5, arg6, arg7, arg8) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T2, T3, T4, T5, T6, T7, T8, T9> Curry<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>(this Func<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9> f, T0 arg0, T1 arg1) => (arg2, arg3, arg4, arg5, arg6, arg7, arg8) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action<T3, T4, T5, T6, T7, T8> Curry<T0, T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T0, T1, T2, T3, T4, T5, T6, T7, T8> f, T0 arg0, T1 arg1, T2 arg2) => (arg3, arg4, arg5, arg6, arg7, arg8) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T3, T4, T5, T6, T7, T8, T9> Curry<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>(this Func<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9> f, T0 arg0, T1 arg1, T2 arg2) => (arg3, arg4, arg5, arg6, arg7, arg8) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action<T4, T5, T6, T7, T8> Curry<T0, T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T0, T1, T2, T3, T4, T5, T6, T7, T8> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3) => (arg4, arg5, arg6, arg7, arg8) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T4, T5, T6, T7, T8, T9> Curry<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>(this Func<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3) => (arg4, arg5, arg6, arg7, arg8) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action<T5, T6, T7, T8> Curry<T0, T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T0, T1, T2, T3, T4, T5, T6, T7, T8> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4) => (arg5, arg6, arg7, arg8) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T5, T6, T7, T8, T9> Curry<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>(this Func<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4) => (arg5, arg6, arg7, arg8) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action<T6, T7, T8> Curry<T0, T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T0, T1, T2, T3, T4, T5, T6, T7, T8> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5) => (arg6, arg7, arg8) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T6, T7, T8, T9> Curry<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>(this Func<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5) => (arg6, arg7, arg8) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action<T7, T8> Curry<T0, T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T0, T1, T2, T3, T4, T5, T6, T7, T8> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6) => (arg7, arg8) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T7, T8, T9> Curry<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>(this Func<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6) => (arg7, arg8) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action<T8> Curry<T0, T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T0, T1, T2, T3, T4, T5, T6, T7, T8> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7) => (arg8) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T8, T9> Curry<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>(this Func<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7) => (arg8) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action Curry<T0, T1, T2, T3, T4, T5, T6, T7, T8>(this Action<T0, T1, T2, T3, T4, T5, T6, T7, T8> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8) => () => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T9> Curry<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>(this Func<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8) => () => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action<T1, T2, T3, T4, T5, T6, T7, T8, T9> Curry<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>(this Action<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9> f, T0 arg0) => (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10> Curry<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(this Func<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10> f, T0 arg0) => (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action<T2, T3, T4, T5, T6, T7, T8, T9> Curry<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>(this Action<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9> f, T0 arg0, T1 arg1) => (arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T2, T3, T4, T5, T6, T7, T8, T9, T10> Curry<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(this Func<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10> f, T0 arg0, T1 arg1) => (arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action<T3, T4, T5, T6, T7, T8, T9> Curry<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>(this Action<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9> f, T0 arg0, T1 arg1, T2 arg2) => (arg3, arg4, arg5, arg6, arg7, arg8, arg9) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T3, T4, T5, T6, T7, T8, T9, T10> Curry<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(this Func<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10> f, T0 arg0, T1 arg1, T2 arg2) => (arg3, arg4, arg5, arg6, arg7, arg8, arg9) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action<T4, T5, T6, T7, T8, T9> Curry<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>(this Action<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3) => (arg4, arg5, arg6, arg7, arg8, arg9) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T4, T5, T6, T7, T8, T9, T10> Curry<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(this Func<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3) => (arg4, arg5, arg6, arg7, arg8, arg9) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action<T5, T6, T7, T8, T9> Curry<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>(this Action<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4) => (arg5, arg6, arg7, arg8, arg9) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T5, T6, T7, T8, T9, T10> Curry<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(this Func<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4) => (arg5, arg6, arg7, arg8, arg9) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action<T6, T7, T8, T9> Curry<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>(this Action<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5) => (arg6, arg7, arg8, arg9) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T6, T7, T8, T9, T10> Curry<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(this Func<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5) => (arg6, arg7, arg8, arg9) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action<T7, T8, T9> Curry<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>(this Action<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6) => (arg7, arg8, arg9) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T7, T8, T9, T10> Curry<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(this Func<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6) => (arg7, arg8, arg9) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action<T8, T9> Curry<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>(this Action<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7) => (arg8, arg9) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T8, T9, T10> Curry<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(this Func<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7) => (arg8, arg9) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action<T9> Curry<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>(this Action<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8) => (arg9) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T9, T10> Curry<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(this Func<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8) => (arg9) => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Action Curry<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>(this Action<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9) => () => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Func<T10> Curry<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(this Func<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10> f, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9) => () => f(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
    }
}
