////////////////////////////////////////////////////// AUTOGENERATED //////////////////////////////////////////////////////
// WARNING: All code changes to this file will be lost upon regeneration.                                                //
// Autogenerated on 2021-01-16 11:21:40:989342                                                                           //
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

using System.Runtime.CompilerServices;
using System;


namespace Unknown6656.Common
{
    public static partial class LINQ
    {

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1) Join<T0, T1>(this T0 t0, T1 t1) => (t0, t1);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2) Join<T0, T1, T2>(this (T0 left, (T1, T2) right) tuple) => (tuple.left, tuple.right.Item1, tuple.right.Item2);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2) Join<T0, T1, T2>(this T0 left, (T1, T2) right) => (left, right.Item1, right.Item2);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2) Join<T0, T1, T2>(this ((T0, T1) left, T2 right) tuple) => (tuple.left.Item1, tuple.left.Item2, tuple.right);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2) Join<T0, T1, T2>(this (T0, T1) left, T2 right) => (left.Item1, left.Item2, right);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2) Join<T0, T1, T2>(this T0 t0, T1 t1, T2 t2) => (t0, t1, t2);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3) Join<T0, T1, T2, T3>(this (T0 left, (T1, T2, T3) right) tuple) => (tuple.left, tuple.right.Item1, tuple.right.Item2, tuple.right.Item3);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3) Join<T0, T1, T2, T3>(this T0 left, (T1, T2, T3) right) => (left, right.Item1, right.Item2, right.Item3);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3) Join<T0, T1, T2, T3>(this ((T0, T1) left, (T2, T3) right) tuple) => (tuple.left.Item1, tuple.left.Item2, tuple.right.Item1, tuple.right.Item2);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3) Join<T0, T1, T2, T3>(this (T0, T1) left, (T2, T3) right) => (left.Item1, left.Item2, right.Item1, right.Item2);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3) Join<T0, T1, T2, T3>(this ((T0, T1, T2) left, T3 right) tuple) => (tuple.left.Item1, tuple.left.Item2, tuple.left.Item3, tuple.right);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3) Join<T0, T1, T2, T3>(this (T0, T1, T2) left, T3 right) => (left.Item1, left.Item2, left.Item3, right);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3) Join<T0, T1, T2, T3>(this T0 t0, T1 t1, T2 t2, T3 t3) => (t0, t1, t2, t3);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4) Join<T0, T1, T2, T3, T4>(this (T0 left, (T1, T2, T3, T4) right) tuple) => (tuple.left, tuple.right.Item1, tuple.right.Item2, tuple.right.Item3, tuple.right.Item4);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4) Join<T0, T1, T2, T3, T4>(this T0 left, (T1, T2, T3, T4) right) => (left, right.Item1, right.Item2, right.Item3, right.Item4);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4) Join<T0, T1, T2, T3, T4>(this ((T0, T1) left, (T2, T3, T4) right) tuple) => (tuple.left.Item1, tuple.left.Item2, tuple.right.Item1, tuple.right.Item2, tuple.right.Item3);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4) Join<T0, T1, T2, T3, T4>(this (T0, T1) left, (T2, T3, T4) right) => (left.Item1, left.Item2, right.Item1, right.Item2, right.Item3);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4) Join<T0, T1, T2, T3, T4>(this ((T0, T1, T2) left, (T3, T4) right) tuple) => (tuple.left.Item1, tuple.left.Item2, tuple.left.Item3, tuple.right.Item1, tuple.right.Item2);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4) Join<T0, T1, T2, T3, T4>(this (T0, T1, T2) left, (T3, T4) right) => (left.Item1, left.Item2, left.Item3, right.Item1, right.Item2);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4) Join<T0, T1, T2, T3, T4>(this ((T0, T1, T2, T3) left, T4 right) tuple) => (tuple.left.Item1, tuple.left.Item2, tuple.left.Item3, tuple.left.Item4, tuple.right);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4) Join<T0, T1, T2, T3, T4>(this (T0, T1, T2, T3) left, T4 right) => (left.Item1, left.Item2, left.Item3, left.Item4, right);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4) Join<T0, T1, T2, T3, T4>(this T0 t0, T1 t1, T2 t2, T3 t3, T4 t4) => (t0, t1, t2, t3, t4);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5) Join<T0, T1, T2, T3, T4, T5>(this (T0 left, (T1, T2, T3, T4, T5) right) tuple) => (tuple.left, tuple.right.Item1, tuple.right.Item2, tuple.right.Item3, tuple.right.Item4, tuple.right.Item5);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5) Join<T0, T1, T2, T3, T4, T5>(this T0 left, (T1, T2, T3, T4, T5) right) => (left, right.Item1, right.Item2, right.Item3, right.Item4, right.Item5);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5) Join<T0, T1, T2, T3, T4, T5>(this ((T0, T1) left, (T2, T3, T4, T5) right) tuple) => (tuple.left.Item1, tuple.left.Item2, tuple.right.Item1, tuple.right.Item2, tuple.right.Item3, tuple.right.Item4);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5) Join<T0, T1, T2, T3, T4, T5>(this (T0, T1) left, (T2, T3, T4, T5) right) => (left.Item1, left.Item2, right.Item1, right.Item2, right.Item3, right.Item4);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5) Join<T0, T1, T2, T3, T4, T5>(this ((T0, T1, T2) left, (T3, T4, T5) right) tuple) => (tuple.left.Item1, tuple.left.Item2, tuple.left.Item3, tuple.right.Item1, tuple.right.Item2, tuple.right.Item3);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5) Join<T0, T1, T2, T3, T4, T5>(this (T0, T1, T2) left, (T3, T4, T5) right) => (left.Item1, left.Item2, left.Item3, right.Item1, right.Item2, right.Item3);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5) Join<T0, T1, T2, T3, T4, T5>(this ((T0, T1, T2, T3) left, (T4, T5) right) tuple) => (tuple.left.Item1, tuple.left.Item2, tuple.left.Item3, tuple.left.Item4, tuple.right.Item1, tuple.right.Item2);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5) Join<T0, T1, T2, T3, T4, T5>(this (T0, T1, T2, T3) left, (T4, T5) right) => (left.Item1, left.Item2, left.Item3, left.Item4, right.Item1, right.Item2);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5) Join<T0, T1, T2, T3, T4, T5>(this ((T0, T1, T2, T3, T4) left, T5 right) tuple) => (tuple.left.Item1, tuple.left.Item2, tuple.left.Item3, tuple.left.Item4, tuple.left.Item5, tuple.right);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5) Join<T0, T1, T2, T3, T4, T5>(this (T0, T1, T2, T3, T4) left, T5 right) => (left.Item1, left.Item2, left.Item3, left.Item4, left.Item5, right);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5) Join<T0, T1, T2, T3, T4, T5>(this T0 t0, T1 t1, T2 t2, T3 t3, T4 t4, T5 t5) => (t0, t1, t2, t3, t4, t5);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6) Join<T0, T1, T2, T3, T4, T5, T6>(this (T0 left, (T1, T2, T3, T4, T5, T6) right) tuple) => (tuple.left, tuple.right.Item1, tuple.right.Item2, tuple.right.Item3, tuple.right.Item4, tuple.right.Item5, tuple.right.Item6);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6) Join<T0, T1, T2, T3, T4, T5, T6>(this T0 left, (T1, T2, T3, T4, T5, T6) right) => (left, right.Item1, right.Item2, right.Item3, right.Item4, right.Item5, right.Item6);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6) Join<T0, T1, T2, T3, T4, T5, T6>(this ((T0, T1) left, (T2, T3, T4, T5, T6) right) tuple) => (tuple.left.Item1, tuple.left.Item2, tuple.right.Item1, tuple.right.Item2, tuple.right.Item3, tuple.right.Item4, tuple.right.Item5);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6) Join<T0, T1, T2, T3, T4, T5, T6>(this (T0, T1) left, (T2, T3, T4, T5, T6) right) => (left.Item1, left.Item2, right.Item1, right.Item2, right.Item3, right.Item4, right.Item5);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6) Join<T0, T1, T2, T3, T4, T5, T6>(this ((T0, T1, T2) left, (T3, T4, T5, T6) right) tuple) => (tuple.left.Item1, tuple.left.Item2, tuple.left.Item3, tuple.right.Item1, tuple.right.Item2, tuple.right.Item3, tuple.right.Item4);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6) Join<T0, T1, T2, T3, T4, T5, T6>(this (T0, T1, T2) left, (T3, T4, T5, T6) right) => (left.Item1, left.Item2, left.Item3, right.Item1, right.Item2, right.Item3, right.Item4);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6) Join<T0, T1, T2, T3, T4, T5, T6>(this ((T0, T1, T2, T3) left, (T4, T5, T6) right) tuple) => (tuple.left.Item1, tuple.left.Item2, tuple.left.Item3, tuple.left.Item4, tuple.right.Item1, tuple.right.Item2, tuple.right.Item3);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6) Join<T0, T1, T2, T3, T4, T5, T6>(this (T0, T1, T2, T3) left, (T4, T5, T6) right) => (left.Item1, left.Item2, left.Item3, left.Item4, right.Item1, right.Item2, right.Item3);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6) Join<T0, T1, T2, T3, T4, T5, T6>(this ((T0, T1, T2, T3, T4) left, (T5, T6) right) tuple) => (tuple.left.Item1, tuple.left.Item2, tuple.left.Item3, tuple.left.Item4, tuple.left.Item5, tuple.right.Item1, tuple.right.Item2);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6) Join<T0, T1, T2, T3, T4, T5, T6>(this (T0, T1, T2, T3, T4) left, (T5, T6) right) => (left.Item1, left.Item2, left.Item3, left.Item4, left.Item5, right.Item1, right.Item2);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6) Join<T0, T1, T2, T3, T4, T5, T6>(this ((T0, T1, T2, T3, T4, T5) left, T6 right) tuple) => (tuple.left.Item1, tuple.left.Item2, tuple.left.Item3, tuple.left.Item4, tuple.left.Item5, tuple.left.Item6, tuple.right);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6) Join<T0, T1, T2, T3, T4, T5, T6>(this (T0, T1, T2, T3, T4, T5) left, T6 right) => (left.Item1, left.Item2, left.Item3, left.Item4, left.Item5, left.Item6, right);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6) Join<T0, T1, T2, T3, T4, T5, T6>(this T0 t0, T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6) => (t0, t1, t2, t3, t4, t5, t6);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7) Join<T0, T1, T2, T3, T4, T5, T6, T7>(this (T0 left, (T1, T2, T3, T4, T5, T6, T7) right) tuple) => (tuple.left, tuple.right.Item1, tuple.right.Item2, tuple.right.Item3, tuple.right.Item4, tuple.right.Item5, tuple.right.Item6, tuple.right.Item7);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7) Join<T0, T1, T2, T3, T4, T5, T6, T7>(this T0 left, (T1, T2, T3, T4, T5, T6, T7) right) => (left, right.Item1, right.Item2, right.Item3, right.Item4, right.Item5, right.Item6, right.Item7);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7) Join<T0, T1, T2, T3, T4, T5, T6, T7>(this ((T0, T1) left, (T2, T3, T4, T5, T6, T7) right) tuple) => (tuple.left.Item1, tuple.left.Item2, tuple.right.Item1, tuple.right.Item2, tuple.right.Item3, tuple.right.Item4, tuple.right.Item5, tuple.right.Item6);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7) Join<T0, T1, T2, T3, T4, T5, T6, T7>(this (T0, T1) left, (T2, T3, T4, T5, T6, T7) right) => (left.Item1, left.Item2, right.Item1, right.Item2, right.Item3, right.Item4, right.Item5, right.Item6);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7) Join<T0, T1, T2, T3, T4, T5, T6, T7>(this ((T0, T1, T2) left, (T3, T4, T5, T6, T7) right) tuple) => (tuple.left.Item1, tuple.left.Item2, tuple.left.Item3, tuple.right.Item1, tuple.right.Item2, tuple.right.Item3, tuple.right.Item4, tuple.right.Item5);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7) Join<T0, T1, T2, T3, T4, T5, T6, T7>(this (T0, T1, T2) left, (T3, T4, T5, T6, T7) right) => (left.Item1, left.Item2, left.Item3, right.Item1, right.Item2, right.Item3, right.Item4, right.Item5);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7) Join<T0, T1, T2, T3, T4, T5, T6, T7>(this ((T0, T1, T2, T3) left, (T4, T5, T6, T7) right) tuple) => (tuple.left.Item1, tuple.left.Item2, tuple.left.Item3, tuple.left.Item4, tuple.right.Item1, tuple.right.Item2, tuple.right.Item3, tuple.right.Item4);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7) Join<T0, T1, T2, T3, T4, T5, T6, T7>(this (T0, T1, T2, T3) left, (T4, T5, T6, T7) right) => (left.Item1, left.Item2, left.Item3, left.Item4, right.Item1, right.Item2, right.Item3, right.Item4);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7) Join<T0, T1, T2, T3, T4, T5, T6, T7>(this ((T0, T1, T2, T3, T4) left, (T5, T6, T7) right) tuple) => (tuple.left.Item1, tuple.left.Item2, tuple.left.Item3, tuple.left.Item4, tuple.left.Item5, tuple.right.Item1, tuple.right.Item2, tuple.right.Item3);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7) Join<T0, T1, T2, T3, T4, T5, T6, T7>(this (T0, T1, T2, T3, T4) left, (T5, T6, T7) right) => (left.Item1, left.Item2, left.Item3, left.Item4, left.Item5, right.Item1, right.Item2, right.Item3);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7) Join<T0, T1, T2, T3, T4, T5, T6, T7>(this ((T0, T1, T2, T3, T4, T5) left, (T6, T7) right) tuple) => (tuple.left.Item1, tuple.left.Item2, tuple.left.Item3, tuple.left.Item4, tuple.left.Item5, tuple.left.Item6, tuple.right.Item1, tuple.right.Item2);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7) Join<T0, T1, T2, T3, T4, T5, T6, T7>(this (T0, T1, T2, T3, T4, T5) left, (T6, T7) right) => (left.Item1, left.Item2, left.Item3, left.Item4, left.Item5, left.Item6, right.Item1, right.Item2);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7) Join<T0, T1, T2, T3, T4, T5, T6, T7>(this ((T0, T1, T2, T3, T4, T5, T6) left, T7 right) tuple) => (tuple.left.Item1, tuple.left.Item2, tuple.left.Item3, tuple.left.Item4, tuple.left.Item5, tuple.left.Item6, tuple.left.Item7, tuple.right);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7) Join<T0, T1, T2, T3, T4, T5, T6, T7>(this (T0, T1, T2, T3, T4, T5, T6) left, T7 right) => (left.Item1, left.Item2, left.Item3, left.Item4, left.Item5, left.Item6, left.Item7, right);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7) Join<T0, T1, T2, T3, T4, T5, T6, T7>(this T0 t0, T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7) => (t0, t1, t2, t3, t4, t5, t6, t7);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7, T8) Join<T0, T1, T2, T3, T4, T5, T6, T7, T8>(this (T0 left, (T1, T2, T3, T4, T5, T6, T7, T8) right) tuple) => (tuple.left, tuple.right.Item1, tuple.right.Item2, tuple.right.Item3, tuple.right.Item4, tuple.right.Item5, tuple.right.Item6, tuple.right.Item7, tuple.right.Item8);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7, T8) Join<T0, T1, T2, T3, T4, T5, T6, T7, T8>(this T0 left, (T1, T2, T3, T4, T5, T6, T7, T8) right) => (left, right.Item1, right.Item2, right.Item3, right.Item4, right.Item5, right.Item6, right.Item7, right.Item8);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7, T8) Join<T0, T1, T2, T3, T4, T5, T6, T7, T8>(this ((T0, T1) left, (T2, T3, T4, T5, T6, T7, T8) right) tuple) => (tuple.left.Item1, tuple.left.Item2, tuple.right.Item1, tuple.right.Item2, tuple.right.Item3, tuple.right.Item4, tuple.right.Item5, tuple.right.Item6, tuple.right.Item7);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7, T8) Join<T0, T1, T2, T3, T4, T5, T6, T7, T8>(this (T0, T1) left, (T2, T3, T4, T5, T6, T7, T8) right) => (left.Item1, left.Item2, right.Item1, right.Item2, right.Item3, right.Item4, right.Item5, right.Item6, right.Item7);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7, T8) Join<T0, T1, T2, T3, T4, T5, T6, T7, T8>(this ((T0, T1, T2) left, (T3, T4, T5, T6, T7, T8) right) tuple) => (tuple.left.Item1, tuple.left.Item2, tuple.left.Item3, tuple.right.Item1, tuple.right.Item2, tuple.right.Item3, tuple.right.Item4, tuple.right.Item5, tuple.right.Item6);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7, T8) Join<T0, T1, T2, T3, T4, T5, T6, T7, T8>(this (T0, T1, T2) left, (T3, T4, T5, T6, T7, T8) right) => (left.Item1, left.Item2, left.Item3, right.Item1, right.Item2, right.Item3, right.Item4, right.Item5, right.Item6);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7, T8) Join<T0, T1, T2, T3, T4, T5, T6, T7, T8>(this ((T0, T1, T2, T3) left, (T4, T5, T6, T7, T8) right) tuple) => (tuple.left.Item1, tuple.left.Item2, tuple.left.Item3, tuple.left.Item4, tuple.right.Item1, tuple.right.Item2, tuple.right.Item3, tuple.right.Item4, tuple.right.Item5);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7, T8) Join<T0, T1, T2, T3, T4, T5, T6, T7, T8>(this (T0, T1, T2, T3) left, (T4, T5, T6, T7, T8) right) => (left.Item1, left.Item2, left.Item3, left.Item4, right.Item1, right.Item2, right.Item3, right.Item4, right.Item5);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7, T8) Join<T0, T1, T2, T3, T4, T5, T6, T7, T8>(this ((T0, T1, T2, T3, T4) left, (T5, T6, T7, T8) right) tuple) => (tuple.left.Item1, tuple.left.Item2, tuple.left.Item3, tuple.left.Item4, tuple.left.Item5, tuple.right.Item1, tuple.right.Item2, tuple.right.Item3, tuple.right.Item4);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7, T8) Join<T0, T1, T2, T3, T4, T5, T6, T7, T8>(this (T0, T1, T2, T3, T4) left, (T5, T6, T7, T8) right) => (left.Item1, left.Item2, left.Item3, left.Item4, left.Item5, right.Item1, right.Item2, right.Item3, right.Item4);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7, T8) Join<T0, T1, T2, T3, T4, T5, T6, T7, T8>(this ((T0, T1, T2, T3, T4, T5) left, (T6, T7, T8) right) tuple) => (tuple.left.Item1, tuple.left.Item2, tuple.left.Item3, tuple.left.Item4, tuple.left.Item5, tuple.left.Item6, tuple.right.Item1, tuple.right.Item2, tuple.right.Item3);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7, T8) Join<T0, T1, T2, T3, T4, T5, T6, T7, T8>(this (T0, T1, T2, T3, T4, T5) left, (T6, T7, T8) right) => (left.Item1, left.Item2, left.Item3, left.Item4, left.Item5, left.Item6, right.Item1, right.Item2, right.Item3);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7, T8) Join<T0, T1, T2, T3, T4, T5, T6, T7, T8>(this ((T0, T1, T2, T3, T4, T5, T6) left, (T7, T8) right) tuple) => (tuple.left.Item1, tuple.left.Item2, tuple.left.Item3, tuple.left.Item4, tuple.left.Item5, tuple.left.Item6, tuple.left.Item7, tuple.right.Item1, tuple.right.Item2);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7, T8) Join<T0, T1, T2, T3, T4, T5, T6, T7, T8>(this (T0, T1, T2, T3, T4, T5, T6) left, (T7, T8) right) => (left.Item1, left.Item2, left.Item3, left.Item4, left.Item5, left.Item6, left.Item7, right.Item1, right.Item2);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7, T8) Join<T0, T1, T2, T3, T4, T5, T6, T7, T8>(this ((T0, T1, T2, T3, T4, T5, T6, T7) left, T8 right) tuple) => (tuple.left.Item1, tuple.left.Item2, tuple.left.Item3, tuple.left.Item4, tuple.left.Item5, tuple.left.Item6, tuple.left.Item7, tuple.left.Item8, tuple.right);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7, T8) Join<T0, T1, T2, T3, T4, T5, T6, T7, T8>(this (T0, T1, T2, T3, T4, T5, T6, T7) left, T8 right) => (left.Item1, left.Item2, left.Item3, left.Item4, left.Item5, left.Item6, left.Item7, left.Item8, right);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7, T8) Join<T0, T1, T2, T3, T4, T5, T6, T7, T8>(this T0 t0, T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7, T8 t8) => (t0, t1, t2, t3, t4, t5, t6, t7, t8);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9) Join<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>(this (T0 left, (T1, T2, T3, T4, T5, T6, T7, T8, T9) right) tuple) => (tuple.left, tuple.right.Item1, tuple.right.Item2, tuple.right.Item3, tuple.right.Item4, tuple.right.Item5, tuple.right.Item6, tuple.right.Item7, tuple.right.Item8, tuple.right.Item9);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9) Join<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>(this T0 left, (T1, T2, T3, T4, T5, T6, T7, T8, T9) right) => (left, right.Item1, right.Item2, right.Item3, right.Item4, right.Item5, right.Item6, right.Item7, right.Item8, right.Item9);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9) Join<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>(this ((T0, T1) left, (T2, T3, T4, T5, T6, T7, T8, T9) right) tuple) => (tuple.left.Item1, tuple.left.Item2, tuple.right.Item1, tuple.right.Item2, tuple.right.Item3, tuple.right.Item4, tuple.right.Item5, tuple.right.Item6, tuple.right.Item7, tuple.right.Item8);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9) Join<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>(this (T0, T1) left, (T2, T3, T4, T5, T6, T7, T8, T9) right) => (left.Item1, left.Item2, right.Item1, right.Item2, right.Item3, right.Item4, right.Item5, right.Item6, right.Item7, right.Item8);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9) Join<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>(this ((T0, T1, T2) left, (T3, T4, T5, T6, T7, T8, T9) right) tuple) => (tuple.left.Item1, tuple.left.Item2, tuple.left.Item3, tuple.right.Item1, tuple.right.Item2, tuple.right.Item3, tuple.right.Item4, tuple.right.Item5, tuple.right.Item6, tuple.right.Item7);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9) Join<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>(this (T0, T1, T2) left, (T3, T4, T5, T6, T7, T8, T9) right) => (left.Item1, left.Item2, left.Item3, right.Item1, right.Item2, right.Item3, right.Item4, right.Item5, right.Item6, right.Item7);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9) Join<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>(this ((T0, T1, T2, T3) left, (T4, T5, T6, T7, T8, T9) right) tuple) => (tuple.left.Item1, tuple.left.Item2, tuple.left.Item3, tuple.left.Item4, tuple.right.Item1, tuple.right.Item2, tuple.right.Item3, tuple.right.Item4, tuple.right.Item5, tuple.right.Item6);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9) Join<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>(this (T0, T1, T2, T3) left, (T4, T5, T6, T7, T8, T9) right) => (left.Item1, left.Item2, left.Item3, left.Item4, right.Item1, right.Item2, right.Item3, right.Item4, right.Item5, right.Item6);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9) Join<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>(this ((T0, T1, T2, T3, T4) left, (T5, T6, T7, T8, T9) right) tuple) => (tuple.left.Item1, tuple.left.Item2, tuple.left.Item3, tuple.left.Item4, tuple.left.Item5, tuple.right.Item1, tuple.right.Item2, tuple.right.Item3, tuple.right.Item4, tuple.right.Item5);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9) Join<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>(this (T0, T1, T2, T3, T4) left, (T5, T6, T7, T8, T9) right) => (left.Item1, left.Item2, left.Item3, left.Item4, left.Item5, right.Item1, right.Item2, right.Item3, right.Item4, right.Item5);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9) Join<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>(this ((T0, T1, T2, T3, T4, T5) left, (T6, T7, T8, T9) right) tuple) => (tuple.left.Item1, tuple.left.Item2, tuple.left.Item3, tuple.left.Item4, tuple.left.Item5, tuple.left.Item6, tuple.right.Item1, tuple.right.Item2, tuple.right.Item3, tuple.right.Item4);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9) Join<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>(this (T0, T1, T2, T3, T4, T5) left, (T6, T7, T8, T9) right) => (left.Item1, left.Item2, left.Item3, left.Item4, left.Item5, left.Item6, right.Item1, right.Item2, right.Item3, right.Item4);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9) Join<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>(this ((T0, T1, T2, T3, T4, T5, T6) left, (T7, T8, T9) right) tuple) => (tuple.left.Item1, tuple.left.Item2, tuple.left.Item3, tuple.left.Item4, tuple.left.Item5, tuple.left.Item6, tuple.left.Item7, tuple.right.Item1, tuple.right.Item2, tuple.right.Item3);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9) Join<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>(this (T0, T1, T2, T3, T4, T5, T6) left, (T7, T8, T9) right) => (left.Item1, left.Item2, left.Item3, left.Item4, left.Item5, left.Item6, left.Item7, right.Item1, right.Item2, right.Item3);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9) Join<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>(this ((T0, T1, T2, T3, T4, T5, T6, T7) left, (T8, T9) right) tuple) => (tuple.left.Item1, tuple.left.Item2, tuple.left.Item3, tuple.left.Item4, tuple.left.Item5, tuple.left.Item6, tuple.left.Item7, tuple.left.Item8, tuple.right.Item1, tuple.right.Item2);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9) Join<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>(this (T0, T1, T2, T3, T4, T5, T6, T7) left, (T8, T9) right) => (left.Item1, left.Item2, left.Item3, left.Item4, left.Item5, left.Item6, left.Item7, left.Item8, right.Item1, right.Item2);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9) Join<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>(this ((T0, T1, T2, T3, T4, T5, T6, T7, T8) left, T9 right) tuple) => (tuple.left.Item1, tuple.left.Item2, tuple.left.Item3, tuple.left.Item4, tuple.left.Item5, tuple.left.Item6, tuple.left.Item7, tuple.left.Item8, tuple.left.Item9, tuple.right);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9) Join<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>(this (T0, T1, T2, T3, T4, T5, T6, T7, T8) left, T9 right) => (left.Item1, left.Item2, left.Item3, left.Item4, left.Item5, left.Item6, left.Item7, left.Item8, left.Item9, right);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9) Join<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>(this T0 t0, T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7, T8 t8, T9 t9) => (t0, t1, t2, t3, t4, t5, t6, t7, t8, t9);
    }
}
