///////////////////////////////////////////////////////////////////////
//             AUTOGENERATED 2020-05-16 17:36:18.858582              //
//   All your changes to this file will be lost upon re-generation.  //
///////////////////////////////////////////////////////////////////////


namespace Unknown6656.Imaging
{
    public partial struct RGBAColor
    {

        /// <summary>
        /// Represents the HTML color 'Transparent' (#00ffffff).
        /// </summary>
        public static RGBAColor Transparent { get; } = 0x00ffffff;

        /// <summary>
        /// Represents the HTML color 'AliceBlue' (#fff0f8ff).
        /// </summary>
        public static RGBAColor AliceBlue { get; } = 0xfff0f8ff;

        /// <summary>
        /// Represents the HTML color 'AntiqueWhite' (#fffaebd7).
        /// </summary>
        public static RGBAColor AntiqueWhite { get; } = 0xfffaebd7;

        /// <summary>
        /// Represents the HTML color 'Aqua' (#ff00ffff).
        /// </summary>
        public static RGBAColor Aqua { get; } = 0xff00ffff;

        /// <summary>
        /// Represents the HTML color 'Aquamarine' (#ff7fffd4).
        /// </summary>
        public static RGBAColor Aquamarine { get; } = 0xff7fffd4;

        /// <summary>
        /// Represents the HTML color 'Azure' (#fff0ffff).
        /// </summary>
        public static RGBAColor Azure { get; } = 0xfff0ffff;

        /// <summary>
        /// Represents the HTML color 'Beige' (#fff5f5dc).
        /// </summary>
        public static RGBAColor Beige { get; } = 0xfff5f5dc;

        /// <summary>
        /// Represents the HTML color 'Bisque' (#ffffe4c4).
        /// </summary>
        public static RGBAColor Bisque { get; } = 0xffffe4c4;

        /// <summary>
        /// Represents the HTML color 'Black' (#ff000000).
        /// </summary>
        public static RGBAColor Black { get; } = 0xff000000;

        /// <summary>
        /// Represents the HTML color 'BlanchedAlmond' (#ffffebcd).
        /// </summary>
        public static RGBAColor BlanchedAlmond { get; } = 0xffffebcd;

        /// <summary>
        /// Represents the HTML color 'Blue' (#ff0000ff).
        /// </summary>
        public static RGBAColor Blue { get; } = 0xff0000ff;

        /// <summary>
        /// Represents the HTML color 'BlueViolet' (#ff8a2be2).
        /// </summary>
        public static RGBAColor BlueViolet { get; } = 0xff8a2be2;

        /// <summary>
        /// Represents the HTML color 'Brown' (#ffa52a2a).
        /// </summary>
        public static RGBAColor Brown { get; } = 0xffa52a2a;

        /// <summary>
        /// Represents the HTML color 'BurlyWood' (#ffdeb887).
        /// </summary>
        public static RGBAColor BurlyWood { get; } = 0xffdeb887;

        /// <summary>
        /// Represents the HTML color 'CadetBlue' (#ff5f9ea0).
        /// </summary>
        public static RGBAColor CadetBlue { get; } = 0xff5f9ea0;

        /// <summary>
        /// Represents the HTML color 'Chartreuse' (#ff7fff00).
        /// </summary>
        public static RGBAColor Chartreuse { get; } = 0xff7fff00;

        /// <summary>
        /// Represents the HTML color 'Chocolate' (#ffd2691e).
        /// </summary>
        public static RGBAColor Chocolate { get; } = 0xffd2691e;

        /// <summary>
        /// Represents the HTML color 'Coral' (#ffff7f50).
        /// </summary>
        public static RGBAColor Coral { get; } = 0xffff7f50;

        /// <summary>
        /// Represents the HTML color 'CornflowerBlue' (#ff6495ed).
        /// </summary>
        public static RGBAColor CornflowerBlue { get; } = 0xff6495ed;

        /// <summary>
        /// Represents the HTML color 'Cornsilk' (#fffff8dc).
        /// </summary>
        public static RGBAColor Cornsilk { get; } = 0xfffff8dc;

        /// <summary>
        /// Represents the HTML color 'Crimson' (#ffdc143c).
        /// </summary>
        public static RGBAColor Crimson { get; } = 0xffdc143c;

        /// <summary>
        /// Represents the HTML color 'Cyan' (#ff00ffff).
        /// </summary>
        public static RGBAColor Cyan { get; } = 0xff00ffff;

        /// <summary>
        /// Represents the HTML color 'DarkBlue' (#ff00008b).
        /// </summary>
        public static RGBAColor DarkBlue { get; } = 0xff00008b;

        /// <summary>
        /// Represents the HTML color 'DarkCyan' (#ff008b8b).
        /// </summary>
        public static RGBAColor DarkCyan { get; } = 0xff008b8b;

        /// <summary>
        /// Represents the HTML color 'DarkGoldenrod' (#ffb8860b).
        /// </summary>
        public static RGBAColor DarkGoldenrod { get; } = 0xffb8860b;

        /// <summary>
        /// Represents the HTML color 'DarkGray' (#ffa9a9a9).
        /// </summary>
        public static RGBAColor DarkGray { get; } = 0xffa9a9a9;

        /// <summary>
        /// Represents the HTML color 'DarkGreen' (#ff006400).
        /// </summary>
        public static RGBAColor DarkGreen { get; } = 0xff006400;

        /// <summary>
        /// Represents the HTML color 'DarkKhaki' (#ffbdb76b).
        /// </summary>
        public static RGBAColor DarkKhaki { get; } = 0xffbdb76b;

        /// <summary>
        /// Represents the HTML color 'DarkMagenta' (#ff8b008b).
        /// </summary>
        public static RGBAColor DarkMagenta { get; } = 0xff8b008b;

        /// <summary>
        /// Represents the HTML color 'DarkOliveGreen' (#ff556b2f).
        /// </summary>
        public static RGBAColor DarkOliveGreen { get; } = 0xff556b2f;

        /// <summary>
        /// Represents the HTML color 'DarkOrange' (#ffff8c00).
        /// </summary>
        public static RGBAColor DarkOrange { get; } = 0xffff8c00;

        /// <summary>
        /// Represents the HTML color 'DarkOrchid' (#ff9932cc).
        /// </summary>
        public static RGBAColor DarkOrchid { get; } = 0xff9932cc;

        /// <summary>
        /// Represents the HTML color 'DarkRed' (#ff8b0000).
        /// </summary>
        public static RGBAColor DarkRed { get; } = 0xff8b0000;

        /// <summary>
        /// Represents the HTML color 'DarkSalmon' (#ffe9967a).
        /// </summary>
        public static RGBAColor DarkSalmon { get; } = 0xffe9967a;

        /// <summary>
        /// Represents the HTML color 'DarkSeaGreen' (#ff8fbc8b).
        /// </summary>
        public static RGBAColor DarkSeaGreen { get; } = 0xff8fbc8b;

        /// <summary>
        /// Represents the HTML color 'DarkSlateBlue' (#ff483d8b).
        /// </summary>
        public static RGBAColor DarkSlateBlue { get; } = 0xff483d8b;

        /// <summary>
        /// Represents the HTML color 'DarkSlateGray' (#ff2f4f4f).
        /// </summary>
        public static RGBAColor DarkSlateGray { get; } = 0xff2f4f4f;

        /// <summary>
        /// Represents the HTML color 'DarkTurquoise' (#ff00ced1).
        /// </summary>
        public static RGBAColor DarkTurquoise { get; } = 0xff00ced1;

        /// <summary>
        /// Represents the HTML color 'DarkViolet' (#ff9400d3).
        /// </summary>
        public static RGBAColor DarkViolet { get; } = 0xff9400d3;

        /// <summary>
        /// Represents the HTML color 'DeepPink' (#ffff1493).
        /// </summary>
        public static RGBAColor DeepPink { get; } = 0xffff1493;

        /// <summary>
        /// Represents the HTML color 'DeepSkyBlue' (#ff00bfff).
        /// </summary>
        public static RGBAColor DeepSkyBlue { get; } = 0xff00bfff;

        /// <summary>
        /// Represents the HTML color 'DimGray' (#ff696969).
        /// </summary>
        public static RGBAColor DimGray { get; } = 0xff696969;

        /// <summary>
        /// Represents the HTML color 'DodgerBlue' (#ff1e90ff).
        /// </summary>
        public static RGBAColor DodgerBlue { get; } = 0xff1e90ff;

        /// <summary>
        /// Represents the HTML color 'Firebrick' (#ffb22222).
        /// </summary>
        public static RGBAColor Firebrick { get; } = 0xffb22222;

        /// <summary>
        /// Represents the HTML color 'FloralWhite' (#fffffaf0).
        /// </summary>
        public static RGBAColor FloralWhite { get; } = 0xfffffaf0;

        /// <summary>
        /// Represents the HTML color 'ForestGreen' (#ff228b22).
        /// </summary>
        public static RGBAColor ForestGreen { get; } = 0xff228b22;

        /// <summary>
        /// Represents the HTML color 'Fuchsia' (#ffff00ff).
        /// </summary>
        public static RGBAColor Fuchsia { get; } = 0xffff00ff;

        /// <summary>
        /// Represents the HTML color 'Gainsboro' (#ffdcdcdc).
        /// </summary>
        public static RGBAColor Gainsboro { get; } = 0xffdcdcdc;

        /// <summary>
        /// Represents the HTML color 'GhostWhite' (#fff8f8ff).
        /// </summary>
        public static RGBAColor GhostWhite { get; } = 0xfff8f8ff;

        /// <summary>
        /// Represents the HTML color 'Gold' (#ffffd700).
        /// </summary>
        public static RGBAColor Gold { get; } = 0xffffd700;

        /// <summary>
        /// Represents the HTML color 'Goldenrod' (#ffdaa520).
        /// </summary>
        public static RGBAColor Goldenrod { get; } = 0xffdaa520;

        /// <summary>
        /// Represents the HTML color 'Gray' (#ff808080).
        /// </summary>
        public static RGBAColor Gray { get; } = 0xff808080;

        /// <summary>
        /// Represents the HTML color 'Green' (#ff008000).
        /// </summary>
        public static RGBAColor Green { get; } = 0xff008000;

        /// <summary>
        /// Represents the HTML color 'GreenYellow' (#ffadff2f).
        /// </summary>
        public static RGBAColor GreenYellow { get; } = 0xffadff2f;

        /// <summary>
        /// Represents the HTML color 'Honeydew' (#fff0fff0).
        /// </summary>
        public static RGBAColor Honeydew { get; } = 0xfff0fff0;

        /// <summary>
        /// Represents the HTML color 'HotPink' (#ffff69b4).
        /// </summary>
        public static RGBAColor HotPink { get; } = 0xffff69b4;

        /// <summary>
        /// Represents the HTML color 'IndianRed' (#ffcd5c5c).
        /// </summary>
        public static RGBAColor IndianRed { get; } = 0xffcd5c5c;

        /// <summary>
        /// Represents the HTML color 'Indigo' (#ff4b0082).
        /// </summary>
        public static RGBAColor Indigo { get; } = 0xff4b0082;

        /// <summary>
        /// Represents the HTML color 'Ivory' (#fffffff0).
        /// </summary>
        public static RGBAColor Ivory { get; } = 0xfffffff0;

        /// <summary>
        /// Represents the HTML color 'Khaki' (#fff0e68c).
        /// </summary>
        public static RGBAColor Khaki { get; } = 0xfff0e68c;

        /// <summary>
        /// Represents the HTML color 'Lavender' (#ffe6e6fa).
        /// </summary>
        public static RGBAColor Lavender { get; } = 0xffe6e6fa;

        /// <summary>
        /// Represents the HTML color 'LavenderBlush' (#fffff0f5).
        /// </summary>
        public static RGBAColor LavenderBlush { get; } = 0xfffff0f5;

        /// <summary>
        /// Represents the HTML color 'LawnGreen' (#ff7cfc00).
        /// </summary>
        public static RGBAColor LawnGreen { get; } = 0xff7cfc00;

        /// <summary>
        /// Represents the HTML color 'LemonChiffon' (#fffffacd).
        /// </summary>
        public static RGBAColor LemonChiffon { get; } = 0xfffffacd;

        /// <summary>
        /// Represents the HTML color 'LightBlue' (#ffadd8e6).
        /// </summary>
        public static RGBAColor LightBlue { get; } = 0xffadd8e6;

        /// <summary>
        /// Represents the HTML color 'LightCoral' (#fff08080).
        /// </summary>
        public static RGBAColor LightCoral { get; } = 0xfff08080;

        /// <summary>
        /// Represents the HTML color 'LightCyan' (#ffe0ffff).
        /// </summary>
        public static RGBAColor LightCyan { get; } = 0xffe0ffff;

        /// <summary>
        /// Represents the HTML color 'LightGoldenrodYellow' (#fffafad2).
        /// </summary>
        public static RGBAColor LightGoldenrodYellow { get; } = 0xfffafad2;

        /// <summary>
        /// Represents the HTML color 'LightGreen' (#ff90ee90).
        /// </summary>
        public static RGBAColor LightGreen { get; } = 0xff90ee90;

        /// <summary>
        /// Represents the HTML color 'LightGray' (#ffd3d3d3).
        /// </summary>
        public static RGBAColor LightGray { get; } = 0xffd3d3d3;

        /// <summary>
        /// Represents the HTML color 'LightPink' (#ffffb6c1).
        /// </summary>
        public static RGBAColor LightPink { get; } = 0xffffb6c1;

        /// <summary>
        /// Represents the HTML color 'LightSalmon' (#ffffa07a).
        /// </summary>
        public static RGBAColor LightSalmon { get; } = 0xffffa07a;

        /// <summary>
        /// Represents the HTML color 'LightSeaGreen' (#ff20b2aa).
        /// </summary>
        public static RGBAColor LightSeaGreen { get; } = 0xff20b2aa;

        /// <summary>
        /// Represents the HTML color 'LightSkyBlue' (#ff87cefa).
        /// </summary>
        public static RGBAColor LightSkyBlue { get; } = 0xff87cefa;

        /// <summary>
        /// Represents the HTML color 'LightSlateGray' (#ff778899).
        /// </summary>
        public static RGBAColor LightSlateGray { get; } = 0xff778899;

        /// <summary>
        /// Represents the HTML color 'LightSteelBlue' (#ffb0c4de).
        /// </summary>
        public static RGBAColor LightSteelBlue { get; } = 0xffb0c4de;

        /// <summary>
        /// Represents the HTML color 'LightYellow' (#ffffffe0).
        /// </summary>
        public static RGBAColor LightYellow { get; } = 0xffffffe0;

        /// <summary>
        /// Represents the HTML color 'Lime' (#ff00ff00).
        /// </summary>
        public static RGBAColor Lime { get; } = 0xff00ff00;

        /// <summary>
        /// Represents the HTML color 'LimeGreen' (#ff32cd32).
        /// </summary>
        public static RGBAColor LimeGreen { get; } = 0xff32cd32;

        /// <summary>
        /// Represents the HTML color 'Linen' (#fffaf0e6).
        /// </summary>
        public static RGBAColor Linen { get; } = 0xfffaf0e6;

        /// <summary>
        /// Represents the HTML color 'Magenta' (#ffff00ff).
        /// </summary>
        public static RGBAColor Magenta { get; } = 0xffff00ff;

        /// <summary>
        /// Represents the HTML color 'Maroon' (#ff800000).
        /// </summary>
        public static RGBAColor Maroon { get; } = 0xff800000;

        /// <summary>
        /// Represents the HTML color 'MediumAquamarine' (#ff66cdaa).
        /// </summary>
        public static RGBAColor MediumAquamarine { get; } = 0xff66cdaa;

        /// <summary>
        /// Represents the HTML color 'MediumBlue' (#ff0000cd).
        /// </summary>
        public static RGBAColor MediumBlue { get; } = 0xff0000cd;

        /// <summary>
        /// Represents the HTML color 'MediumOrchid' (#ffba55d3).
        /// </summary>
        public static RGBAColor MediumOrchid { get; } = 0xffba55d3;

        /// <summary>
        /// Represents the HTML color 'MediumPurple' (#ff9370db).
        /// </summary>
        public static RGBAColor MediumPurple { get; } = 0xff9370db;

        /// <summary>
        /// Represents the HTML color 'MediumSeaGreen' (#ff3cb371).
        /// </summary>
        public static RGBAColor MediumSeaGreen { get; } = 0xff3cb371;

        /// <summary>
        /// Represents the HTML color 'MediumSlateBlue' (#ff7b68ee).
        /// </summary>
        public static RGBAColor MediumSlateBlue { get; } = 0xff7b68ee;

        /// <summary>
        /// Represents the HTML color 'MediumSpringGreen' (#ff00fa9a).
        /// </summary>
        public static RGBAColor MediumSpringGreen { get; } = 0xff00fa9a;

        /// <summary>
        /// Represents the HTML color 'MediumTurquoise' (#ff48d1cc).
        /// </summary>
        public static RGBAColor MediumTurquoise { get; } = 0xff48d1cc;

        /// <summary>
        /// Represents the HTML color 'MediumVioletRed' (#ffc71585).
        /// </summary>
        public static RGBAColor MediumVioletRed { get; } = 0xffc71585;

        /// <summary>
        /// Represents the HTML color 'MidnightBlue' (#ff191970).
        /// </summary>
        public static RGBAColor MidnightBlue { get; } = 0xff191970;

        /// <summary>
        /// Represents the HTML color 'MintCream' (#fff5fffa).
        /// </summary>
        public static RGBAColor MintCream { get; } = 0xfff5fffa;

        /// <summary>
        /// Represents the HTML color 'MistyRose' (#ffffe4e1).
        /// </summary>
        public static RGBAColor MistyRose { get; } = 0xffffe4e1;

        /// <summary>
        /// Represents the HTML color 'Moccasin' (#ffffe4b5).
        /// </summary>
        public static RGBAColor Moccasin { get; } = 0xffffe4b5;

        /// <summary>
        /// Represents the HTML color 'NavajoWhite' (#ffffdead).
        /// </summary>
        public static RGBAColor NavajoWhite { get; } = 0xffffdead;

        /// <summary>
        /// Represents the HTML color 'Navy' (#ff000080).
        /// </summary>
        public static RGBAColor Navy { get; } = 0xff000080;

        /// <summary>
        /// Represents the HTML color 'OldLace' (#fffdf5e6).
        /// </summary>
        public static RGBAColor OldLace { get; } = 0xfffdf5e6;

        /// <summary>
        /// Represents the HTML color 'Olive' (#ff808000).
        /// </summary>
        public static RGBAColor Olive { get; } = 0xff808000;

        /// <summary>
        /// Represents the HTML color 'OliveDrab' (#ff6b8e23).
        /// </summary>
        public static RGBAColor OliveDrab { get; } = 0xff6b8e23;

        /// <summary>
        /// Represents the HTML color 'Orange' (#ffffa500).
        /// </summary>
        public static RGBAColor Orange { get; } = 0xffffa500;

        /// <summary>
        /// Represents the HTML color 'OrangeRed' (#ffff4500).
        /// </summary>
        public static RGBAColor OrangeRed { get; } = 0xffff4500;

        /// <summary>
        /// Represents the HTML color 'Orchid' (#ffda70d6).
        /// </summary>
        public static RGBAColor Orchid { get; } = 0xffda70d6;

        /// <summary>
        /// Represents the HTML color 'PaleGoldenrod' (#ffeee8aa).
        /// </summary>
        public static RGBAColor PaleGoldenrod { get; } = 0xffeee8aa;

        /// <summary>
        /// Represents the HTML color 'PaleGreen' (#ff98fb98).
        /// </summary>
        public static RGBAColor PaleGreen { get; } = 0xff98fb98;

        /// <summary>
        /// Represents the HTML color 'PaleTurquoise' (#ffafeeee).
        /// </summary>
        public static RGBAColor PaleTurquoise { get; } = 0xffafeeee;

        /// <summary>
        /// Represents the HTML color 'PaleVioletRed' (#ffdb7093).
        /// </summary>
        public static RGBAColor PaleVioletRed { get; } = 0xffdb7093;

        /// <summary>
        /// Represents the HTML color 'PapayaWhip' (#ffffefd5).
        /// </summary>
        public static RGBAColor PapayaWhip { get; } = 0xffffefd5;

        /// <summary>
        /// Represents the HTML color 'PeachPuff' (#ffffdab9).
        /// </summary>
        public static RGBAColor PeachPuff { get; } = 0xffffdab9;

        /// <summary>
        /// Represents the HTML color 'Peru' (#ffcd853f).
        /// </summary>
        public static RGBAColor Peru { get; } = 0xffcd853f;

        /// <summary>
        /// Represents the HTML color 'Pink' (#ffffc0cb).
        /// </summary>
        public static RGBAColor Pink { get; } = 0xffffc0cb;

        /// <summary>
        /// Represents the HTML color 'Plum' (#ffdda0dd).
        /// </summary>
        public static RGBAColor Plum { get; } = 0xffdda0dd;

        /// <summary>
        /// Represents the HTML color 'PowderBlue' (#ffb0e0e6).
        /// </summary>
        public static RGBAColor PowderBlue { get; } = 0xffb0e0e6;

        /// <summary>
        /// Represents the HTML color 'Purple' (#ff800080).
        /// </summary>
        public static RGBAColor Purple { get; } = 0xff800080;

        /// <summary>
        /// Represents the HTML color 'Red' (#ffff0000).
        /// </summary>
        public static RGBAColor Red { get; } = 0xffff0000;

        /// <summary>
        /// Represents the HTML color 'RosyBrown' (#ffbc8f8f).
        /// </summary>
        public static RGBAColor RosyBrown { get; } = 0xffbc8f8f;

        /// <summary>
        /// Represents the HTML color 'RoyalBlue' (#ff4169e1).
        /// </summary>
        public static RGBAColor RoyalBlue { get; } = 0xff4169e1;

        /// <summary>
        /// Represents the HTML color 'SaddleBrown' (#ff8b4513).
        /// </summary>
        public static RGBAColor SaddleBrown { get; } = 0xff8b4513;

        /// <summary>
        /// Represents the HTML color 'Salmon' (#fffa8072).
        /// </summary>
        public static RGBAColor Salmon { get; } = 0xfffa8072;

        /// <summary>
        /// Represents the HTML color 'SandyBrown' (#fff4a460).
        /// </summary>
        public static RGBAColor SandyBrown { get; } = 0xfff4a460;

        /// <summary>
        /// Represents the HTML color 'SeaGreen' (#ff2e8b57).
        /// </summary>
        public static RGBAColor SeaGreen { get; } = 0xff2e8b57;

        /// <summary>
        /// Represents the HTML color 'SeaShell' (#fffff5ee).
        /// </summary>
        public static RGBAColor SeaShell { get; } = 0xfffff5ee;

        /// <summary>
        /// Represents the HTML color 'Sienna' (#ffa0522d).
        /// </summary>
        public static RGBAColor Sienna { get; } = 0xffa0522d;

        /// <summary>
        /// Represents the HTML color 'Silver' (#ffc0c0c0).
        /// </summary>
        public static RGBAColor Silver { get; } = 0xffc0c0c0;

        /// <summary>
        /// Represents the HTML color 'SkyBlue' (#ff87ceeb).
        /// </summary>
        public static RGBAColor SkyBlue { get; } = 0xff87ceeb;

        /// <summary>
        /// Represents the HTML color 'SlateBlue' (#ff6a5acd).
        /// </summary>
        public static RGBAColor SlateBlue { get; } = 0xff6a5acd;

        /// <summary>
        /// Represents the HTML color 'SlateGray' (#ff708090).
        /// </summary>
        public static RGBAColor SlateGray { get; } = 0xff708090;

        /// <summary>
        /// Represents the HTML color 'Snow' (#fffffafa).
        /// </summary>
        public static RGBAColor Snow { get; } = 0xfffffafa;

        /// <summary>
        /// Represents the HTML color 'SpringGreen' (#ff00ff7f).
        /// </summary>
        public static RGBAColor SpringGreen { get; } = 0xff00ff7f;

        /// <summary>
        /// Represents the HTML color 'SteelBlue' (#ff4682b4).
        /// </summary>
        public static RGBAColor SteelBlue { get; } = 0xff4682b4;

        /// <summary>
        /// Represents the HTML color 'Tan' (#ffd2b48c).
        /// </summary>
        public static RGBAColor Tan { get; } = 0xffd2b48c;

        /// <summary>
        /// Represents the HTML color 'Teal' (#ff008080).
        /// </summary>
        public static RGBAColor Teal { get; } = 0xff008080;

        /// <summary>
        /// Represents the HTML color 'Thistle' (#ffd8bfd8).
        /// </summary>
        public static RGBAColor Thistle { get; } = 0xffd8bfd8;

        /// <summary>
        /// Represents the HTML color 'Tomato' (#ffff6347).
        /// </summary>
        public static RGBAColor Tomato { get; } = 0xffff6347;

        /// <summary>
        /// Represents the HTML color 'Turquoise' (#ff40e0d0).
        /// </summary>
        public static RGBAColor Turquoise { get; } = 0xff40e0d0;

        /// <summary>
        /// Represents the HTML color 'Violet' (#ffee82ee).
        /// </summary>
        public static RGBAColor Violet { get; } = 0xffee82ee;

        /// <summary>
        /// Represents the HTML color 'Wheat' (#fff5deb3).
        /// </summary>
        public static RGBAColor Wheat { get; } = 0xfff5deb3;

        /// <summary>
        /// Represents the HTML color 'White' (#ffffffff).
        /// </summary>
        public static RGBAColor White { get; } = 0xffffffff;

        /// <summary>
        /// Represents the HTML color 'WhiteSmoke' (#fff5f5f5).
        /// </summary>
        public static RGBAColor WhiteSmoke { get; } = 0xfff5f5f5;

        /// <summary>
        /// Represents the HTML color 'Yellow' (#ffffff00).
        /// </summary>
        public static RGBAColor Yellow { get; } = 0xffffff00;

        /// <summary>
        /// Represents the HTML color 'YellowGreen' (#ff9acd32).
        /// </summary>
        public static RGBAColor YellowGreen { get; } = 0xff9acd32;
    }
}
