///////////////////////////////////////////////////////////////////////
//             AUTOGENERATED 2022-02-13 01:14:54.976253              //
//   All your changes to this file will be lost upon re-generation.  //
///////////////////////////////////////////////////////////////////////

using System.Runtime.CompilerServices;
using System;

namespace Unknown6656.IO;


public unsafe sealed partial class UnsafeFunctionPointer
{
    public Action AsAction()
        => new(Invoke);

    public Action<T0> AsAction<T0>()
        => new(Invoke);

    public Action<T0, T1> AsAction<T0, T1>()
        => new(Invoke);

    public Action<T0, T1, T2> AsAction<T0, T1, T2>()
        => new(Invoke);

    public Action<T0, T1, T2, T3> AsAction<T0, T1, T2, T3>()
        => new(Invoke);

    public Action<T0, T1, T2, T3, T4> AsAction<T0, T1, T2, T3, T4>()
        => new(Invoke);

    public Action<T0, T1, T2, T3, T4, T5> AsAction<T0, T1, T2, T3, T4, T5>()
        => new(Invoke);

    public Action<T0, T1, T2, T3, T4, T5, T6> AsAction<T0, T1, T2, T3, T4, T5, T6>()
        => new(Invoke);

    public Action<T0, T1, T2, T3, T4, T5, T6, T7> AsAction<T0, T1, T2, T3, T4, T5, T6, T7>()
        => new(Invoke);

    public Action<T0, T1, T2, T3, T4, T5, T6, T7, T8> AsAction<T0, T1, T2, T3, T4, T5, T6, T7, T8>()
        => new(Invoke);

    public Action<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9> AsAction<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>()
        => new(Invoke);

    public Action<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10> AsAction<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>()
        => new(Invoke);

    public Action<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11> AsAction<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>()
        => new(Invoke);

    public Action<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12> AsAction<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>()
        => new(Invoke);

    public Action<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13> AsAction<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>()
        => new(Invoke);

    public Action<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14> AsAction<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>()
        => new(Invoke);

    public Action<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15> AsAction<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>()
        => new(Invoke);

    public Func<T> AsFunction<T>() =>
        new(Invoke<T>);

    public Func<T0, T> AsFunction<T0, T>() =>
        new(Invoke<T0, T>);

    public Func<T0, T1, T> AsFunction<T0, T1, T>() =>
        new(Invoke<T0, T1, T>);

    public Func<T0, T1, T2, T> AsFunction<T0, T1, T2, T>() =>
        new(Invoke<T0, T1, T2, T>);

    public Func<T0, T1, T2, T3, T> AsFunction<T0, T1, T2, T3, T>() =>
        new(Invoke<T0, T1, T2, T3, T>);

    public Func<T0, T1, T2, T3, T4, T> AsFunction<T0, T1, T2, T3, T4, T>() =>
        new(Invoke<T0, T1, T2, T3, T4, T>);

    public Func<T0, T1, T2, T3, T4, T5, T> AsFunction<T0, T1, T2, T3, T4, T5, T>() =>
        new(Invoke<T0, T1, T2, T3, T4, T5, T>);

    public Func<T0, T1, T2, T3, T4, T5, T6, T> AsFunction<T0, T1, T2, T3, T4, T5, T6, T>() =>
        new(Invoke<T0, T1, T2, T3, T4, T5, T6, T>);

    public Func<T0, T1, T2, T3, T4, T5, T6, T7, T> AsFunction<T0, T1, T2, T3, T4, T5, T6, T7, T>() =>
        new(Invoke<T0, T1, T2, T3, T4, T5, T6, T7, T>);

    public Func<T0, T1, T2, T3, T4, T5, T6, T7, T8, T> AsFunction<T0, T1, T2, T3, T4, T5, T6, T7, T8, T>() =>
        new(Invoke<T0, T1, T2, T3, T4, T5, T6, T7, T8, T>);

    public Func<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T> AsFunction<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T>() =>
        new(Invoke<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T>);

    public Func<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T> AsFunction<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T>() =>
        new(Invoke<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T>);

    public Func<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T> AsFunction<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T>() =>
        new(Invoke<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T>);

    public Func<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T> AsFunction<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T>() =>
        new(Invoke<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T>);

    public Func<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T> AsFunction<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T>() =>
        new(Invoke<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T>);

    public Func<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T> AsFunction<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T>() =>
        new(Invoke<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T>);

    public Func<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T> AsFunction<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T>() =>
        new(Invoke<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T>);

    public delegate*<T> AsUnsafe<T>() =>
        (delegate*<T>)BufferAddress;

    public delegate*<T0, T> AsUnsafe<T0, T>() =>
        (delegate*<T0, T>)BufferAddress;

    public delegate*<T0, T1, T> AsUnsafe<T0, T1, T>() =>
        (delegate*<T0, T1, T>)BufferAddress;

    public delegate*<T0, T1, T2, T> AsUnsafe<T0, T1, T2, T>() =>
        (delegate*<T0, T1, T2, T>)BufferAddress;

    public delegate*<T0, T1, T2, T3, T> AsUnsafe<T0, T1, T2, T3, T>() =>
        (delegate*<T0, T1, T2, T3, T>)BufferAddress;

    public delegate*<T0, T1, T2, T3, T4, T> AsUnsafe<T0, T1, T2, T3, T4, T>() =>
        (delegate*<T0, T1, T2, T3, T4, T>)BufferAddress;

    public delegate*<T0, T1, T2, T3, T4, T5, T> AsUnsafe<T0, T1, T2, T3, T4, T5, T>() =>
        (delegate*<T0, T1, T2, T3, T4, T5, T>)BufferAddress;

    public delegate*<T0, T1, T2, T3, T4, T5, T6, T> AsUnsafe<T0, T1, T2, T3, T4, T5, T6, T>() =>
        (delegate*<T0, T1, T2, T3, T4, T5, T6, T>)BufferAddress;

    public delegate*<T0, T1, T2, T3, T4, T5, T6, T7, T> AsUnsafe<T0, T1, T2, T3, T4, T5, T6, T7, T>() =>
        (delegate*<T0, T1, T2, T3, T4, T5, T6, T7, T>)BufferAddress;

    public delegate*<T0, T1, T2, T3, T4, T5, T6, T7, T8, T> AsUnsafe<T0, T1, T2, T3, T4, T5, T6, T7, T8, T>() =>
        (delegate*<T0, T1, T2, T3, T4, T5, T6, T7, T8, T>)BufferAddress;

    public delegate*<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T> AsUnsafe<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T>() =>
        (delegate*<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T>)BufferAddress;

    public delegate*<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T> AsUnsafe<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T>() =>
        (delegate*<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T>)BufferAddress;

    public delegate*<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T> AsUnsafe<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T>() =>
        (delegate*<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T>)BufferAddress;

    public delegate*<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T> AsUnsafe<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T>() =>
        (delegate*<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T>)BufferAddress;

    public delegate*<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T> AsUnsafe<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T>() =>
        (delegate*<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T>)BufferAddress;

    public delegate*<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T> AsUnsafe<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T>() =>
        (delegate*<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T>)BufferAddress;

    public delegate*<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T> AsUnsafe<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T>() =>
        (delegate*<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T>)BufferAddress;

    public void Invoke() =>
        ((delegate*<void>)BufferAddress)();

    public T Invoke<T>() =>
        ((delegate*<T>)BufferAddress)();

    public void Invoke<T0>(T0 t0) =>
        ((delegate*<T0, void>)BufferAddress)(t0);

    public T Invoke<T0, T>(T0 t0) =>
        ((delegate*<T0, T>)BufferAddress)(t0);

    public void Invoke<T0, T1>(T0 t0, T1 t1) =>
        ((delegate*<T0, T1, void>)BufferAddress)(t0, t1);

    public T Invoke<T0, T1, T>(T0 t0, T1 t1) =>
        ((delegate*<T0, T1, T>)BufferAddress)(t0, t1);

    public void Invoke<T0, T1, T2>(T0 t0, T1 t1, T2 t2) =>
        ((delegate*<T0, T1, T2, void>)BufferAddress)(t0, t1, t2);

    public T Invoke<T0, T1, T2, T>(T0 t0, T1 t1, T2 t2) =>
        ((delegate*<T0, T1, T2, T>)BufferAddress)(t0, t1, t2);

    public void Invoke<T0, T1, T2, T3>(T0 t0, T1 t1, T2 t2, T3 t3) =>
        ((delegate*<T0, T1, T2, T3, void>)BufferAddress)(t0, t1, t2, t3);

    public T Invoke<T0, T1, T2, T3, T>(T0 t0, T1 t1, T2 t2, T3 t3) =>
        ((delegate*<T0, T1, T2, T3, T>)BufferAddress)(t0, t1, t2, t3);

    public void Invoke<T0, T1, T2, T3, T4>(T0 t0, T1 t1, T2 t2, T3 t3, T4 t4) =>
        ((delegate*<T0, T1, T2, T3, T4, void>)BufferAddress)(t0, t1, t2, t3, t4);

    public T Invoke<T0, T1, T2, T3, T4, T>(T0 t0, T1 t1, T2 t2, T3 t3, T4 t4) =>
        ((delegate*<T0, T1, T2, T3, T4, T>)BufferAddress)(t0, t1, t2, t3, t4);

    public void Invoke<T0, T1, T2, T3, T4, T5>(T0 t0, T1 t1, T2 t2, T3 t3, T4 t4, T5 t5) =>
        ((delegate*<T0, T1, T2, T3, T4, T5, void>)BufferAddress)(t0, t1, t2, t3, t4, t5);

    public T Invoke<T0, T1, T2, T3, T4, T5, T>(T0 t0, T1 t1, T2 t2, T3 t3, T4 t4, T5 t5) =>
        ((delegate*<T0, T1, T2, T3, T4, T5, T>)BufferAddress)(t0, t1, t2, t3, t4, t5);

    public void Invoke<T0, T1, T2, T3, T4, T5, T6>(T0 t0, T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6) =>
        ((delegate*<T0, T1, T2, T3, T4, T5, T6, void>)BufferAddress)(t0, t1, t2, t3, t4, t5, t6);

    public T Invoke<T0, T1, T2, T3, T4, T5, T6, T>(T0 t0, T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6) =>
        ((delegate*<T0, T1, T2, T3, T4, T5, T6, T>)BufferAddress)(t0, t1, t2, t3, t4, t5, t6);

    public void Invoke<T0, T1, T2, T3, T4, T5, T6, T7>(T0 t0, T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7) =>
        ((delegate*<T0, T1, T2, T3, T4, T5, T6, T7, void>)BufferAddress)(t0, t1, t2, t3, t4, t5, t6, t7);

    public T Invoke<T0, T1, T2, T3, T4, T5, T6, T7, T>(T0 t0, T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7) =>
        ((delegate*<T0, T1, T2, T3, T4, T5, T6, T7, T>)BufferAddress)(t0, t1, t2, t3, t4, t5, t6, t7);

    public void Invoke<T0, T1, T2, T3, T4, T5, T6, T7, T8>(T0 t0, T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7, T8 t8) =>
        ((delegate*<T0, T1, T2, T3, T4, T5, T6, T7, T8, void>)BufferAddress)(t0, t1, t2, t3, t4, t5, t6, t7, t8);

    public T Invoke<T0, T1, T2, T3, T4, T5, T6, T7, T8, T>(T0 t0, T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7, T8 t8) =>
        ((delegate*<T0, T1, T2, T3, T4, T5, T6, T7, T8, T>)BufferAddress)(t0, t1, t2, t3, t4, t5, t6, t7, t8);

    public void Invoke<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>(T0 t0, T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7, T8 t8, T9 t9) =>
        ((delegate*<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, void>)BufferAddress)(t0, t1, t2, t3, t4, t5, t6, t7, t8, t9);

    public T Invoke<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T>(T0 t0, T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7, T8 t8, T9 t9) =>
        ((delegate*<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T>)BufferAddress)(t0, t1, t2, t3, t4, t5, t6, t7, t8, t9);

    public void Invoke<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(T0 t0, T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7, T8 t8, T9 t9, T10 t10) =>
        ((delegate*<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, void>)BufferAddress)(t0, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10);

    public T Invoke<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T>(T0 t0, T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7, T8 t8, T9 t9, T10 t10) =>
        ((delegate*<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T>)BufferAddress)(t0, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10);

    public void Invoke<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>(T0 t0, T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7, T8 t8, T9 t9, T10 t10, T11 t11) =>
        ((delegate*<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, void>)BufferAddress)(t0, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11);

    public T Invoke<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T>(T0 t0, T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7, T8 t8, T9 t9, T10 t10, T11 t11) =>
        ((delegate*<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T>)BufferAddress)(t0, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11);

    public void Invoke<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>(T0 t0, T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7, T8 t8, T9 t9, T10 t10, T11 t11, T12 t12) =>
        ((delegate*<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, void>)BufferAddress)(t0, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12);

    public T Invoke<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T>(T0 t0, T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7, T8 t8, T9 t9, T10 t10, T11 t11, T12 t12) =>
        ((delegate*<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T>)BufferAddress)(t0, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12);

    public void Invoke<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>(T0 t0, T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7, T8 t8, T9 t9, T10 t10, T11 t11, T12 t12, T13 t13) =>
        ((delegate*<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, void>)BufferAddress)(t0, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13);

    public T Invoke<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T>(T0 t0, T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7, T8 t8, T9 t9, T10 t10, T11 t11, T12 t12, T13 t13) =>
        ((delegate*<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T>)BufferAddress)(t0, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13);

    public void Invoke<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>(T0 t0, T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7, T8 t8, T9 t9, T10 t10, T11 t11, T12 t12, T13 t13, T14 t14) =>
        ((delegate*<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, void>)BufferAddress)(t0, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14);

    public T Invoke<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T>(T0 t0, T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7, T8 t8, T9 t9, T10 t10, T11 t11, T12 t12, T13 t13, T14 t14) =>
        ((delegate*<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T>)BufferAddress)(t0, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14);

    public void Invoke<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>(T0 t0, T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7, T8 t8, T9 t9, T10 t10, T11 t11, T12 t12, T13 t13, T14 t14, T15 t15) =>
        ((delegate*<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, void>)BufferAddress)(t0, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15);

    public T Invoke<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T>(T0 t0, T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7, T8 t8, T9 t9, T10 t10, T11 t11, T12 t12, T13 t13, T14 t14, T15 t15) =>
        ((delegate*<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T>)BufferAddress)(t0, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15);

}
